[phases.install]
cmds = ['composer update --no-dev --optimize-autoloader', 'npm ci', 'npm run build']

[start]
cmd = 'mkdir -p /var/log/nginx && php artisan migrate --force && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /etc/nginx.conf ; cat -n /etc/nginx.conf'
