# Use official PHP image
FROM php:8.2-cli

# Install dependencies
RUN apt-get update && \
    apt-get install -y unzip curl libpng-dev libonig-dev libxml2-dev && \
    docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set the working directory
WORKDIR /var/www/html

# Copy the application code
COPY . .

# Install Laravel dependencies
RUN composer install

# Generate application key
RUN php artisan key:generate

# Expose the port for Laravel
EXPOSE 8000

# Start Laravel server
CMD php artisan serve --host=0.0.0.0 --port=8000
