version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:3000
    command: ["npm", "run", "dev", "--", "--host"]

networks:
  app-network:
    driver: bridge
