services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend_container
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_container
      - DB_PORT=5432
      - DB_DATABASE=investment_db
      - DB_USERNAME=your_username
      - DB_PASSWORD=your_password
    depends_on:
      - postgres


  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app

volumes:
  postgres_data:
